bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL,)

images/urls.py
from django.urls import path
from . import views
app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse 

# Create your models here.
# Model to store Image retrieved from different sites
class Image(models.Model):
     user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="images_created", on_delete= models.CASCADE) # this specifies a one-to-many relationship
     title = models.CharField(max_length=5000) # a title for the image
     slug = models.SlugField(max_length=5000, blank=True) #  A short label that contains only letters, numbers, underscores, or hyphens to be used for building beautiful SEO-friendly URLs. 
     url = models.URLField() #  The original URL for this image. 
     image = models.ImageField(upload_to='images/%Y/%m/%d/') #  The image file. 
     description = models.TextField(blank=True) #  An optional description for the image. 
     created = models.DateField(auto_now_add=True, db_index = True) # The date and time that indicate when the object was created in the database
     users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True) # ManyToMany relationship

     def __str__(self):
         return self.title


    # this function automatically generates image slug when there is none provided.
     def save(self, *args, **kwargs):
        if not self.slug:
               self.slug = slugify(self.title)
        super().save(*args, **kwargs)

     def get_absolute_url(self):
          return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }


# validation function  to check whether the given URL provides a valid image file.
    def clean_url(self):
        url =self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url


def save(self, force_insert=False,
                force_update=False,
                commit = True):
    image = super().save(commit=False)
    image_url = self.cleaned_data['url']
    name = slugify(image.title)
    extension = image_url.rsplit('.', 1)[1].lower()
    image_name =f'{name}.{extension}'


    # download image from the given URL
    response =request.urlopen(image_url)
    image.image.save(image_name, ContentFile(response.read()),
                            save=False)

    if commit:
        image.save()
    return Image

images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST

# Create your views here.
@login_required # login_required decorator is used to prevent access for unauthenticated users
def image_create(request):
    if request.method =='POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # If the form data is valid create a new Image instance, 
            # but prevent the object from being saved to the database,
            # yet by passing commit=False to the form's save() method. 
            cd = form.cleaned_data 
            new_item = form.save(commit=False)

            # assign the current user to the new image object. 
            # This is how you can know who uploaded each image
            new_item.user = request.user
            new_item.save() # save the image object to the database. 
            messages.success(request, 'Image added successfully') # create a success message using the Django messaging framework 

            # redirect to new created item detail view 
            return redirect(new_item.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)

    return render(request, 'images/image/create.html', {'section': 'images', 'form': form})


# view to display an image
def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    return render(request, 'images/image/detail.html',{'section': 'images', 'image': image})

# views for users to like images
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(require.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'OK'})
        except:
            pass
    return JsonResponse({'status':'error'})

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Bookmark an image {% endblock %}

{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method = "post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type = "submit" value="Bookmark it!">
</form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}
  {% if image.image %}
  <a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
  </a>
  {% else %}
  <p></p>
  {% endif %}
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
      {% for user in users_like %}
        <div>
          <img src="{{ user.profile.photo.url }}">
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' :
          'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}